### ISSUE TITLE
[AI Bundle] Unresolved dependencies

### ISSUE THREAD

**Issue by xprojects-de** [symfony/ai#1075]
The AI ​​bundle configuration has dependencies on, for example, `use Symfony\AI\Store\Bridge\Postgres\Distance as PostgresDistance` and `use Symfony\AI\Store\Bridge\Redis\Distance`, which are now standalone packages and may not be installed.

```
The enum class "Symfony\AI\Store\Bridge\Postgres\Distance" does not exist i  
  n /Users/.../vendor/symfony/ai-bundle/src/../co  
  nfig/options.php (which is being imported from "/Users/ .../vendor/symfony/ai-bundle/src/AiBundle.php").
```

https://github.com/symfony/ai/blob/5dd24d0ea68f9065e374085f1cd09d28ff531d42/src/ai-bundle/config/options.php#L21

**Comment by OskarStark** [comment]
Should be fixed, right?

**Comment by Huluti** [comment]
@OskarStark Strangely on my side I still have the issue.
That's strange because the new deps are well in my composer.lock... 
I've tried to remove entirely the cache folder to be sure.

<img width="622" height="881" alt="Image" src="https://github.com/user-attachments/assets/a8675490-a1fa-46a7-8f89-763e8352525f" />

**Comment by xprojects-de** [comment]
- Root composer.json requires symfony/ai-redis-store @dev -> satisfiable by symfony/ai-redis-store[dev-main, 0.x-dev (alias of dev-main)].
     - symfony/ai-redis-store[dev-main, 0.x-dev] require ext-redis * -> it is missing from your system. Install or enable PHP's redis extension.

I think this approach requires that all extensions are always installed. Building the cache in the live system would cause problems.

**Comment by Huluti** [comment]
On my side I have the required extensions because if I require manyally the two deps (postgre and redis) then I don't have any remaining errors

**Comment by VincentLanglet** [comment]
Might be worth to reopen this issue @OskarStark ?

I still get the error
```
In FileLoader.php line 177:
!!
!!    The enum class "Symfony\AI\Store\Bridge\Postgres\Distance" does not exist i
!!    n /app/vendor/symfony/ai-bundle/src/../config/options.php (which is being i
!!    mported from "/app/vendor/symfony/ai-bundle/src/AiBundle.php").
!!
!!
!!  In EnumNodeDefinition.php line 52:
!!
!!    The enum class "Symfony\AI\Store\Bridge\Postgres\Distance" does not exist.
!!
```

You added those dependencies into `require-dev`, I don't see how it resolve the issue since they are not in the require section.

But on the other side I don't think those libs should be in the require section since they are only bridge (and maybe not used). Maybe there is something to change in the config definition ?

**Comment by xprojects-de** [comment]
I think the idea behind it is to build the cache in a local environment. But I think it should also be possible in a live environment. I also wouldn't consider to include the dependencies in the `require` statement. I also think the configuration logic should be adapted.

**Comment by OskarStark** [comment]
Yes there is something wrong

**Comment by OskarStark** [comment]
What do you guys think?
https://github.com/symfony/ai/pull/1082
